# Generated by Django 1.11.2 on 2017-07-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_auto_20170630_1523'),
        ('poker', '0010_auto_20170630_1453'),
    ]

    operations = [
    ]
