# Generated by Django 1.11.13 on 2018-07-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0024_pokertable_sidebets_enabled'),
        ('poker', '0024_pokertournament_party_leader'),
    ]

    operations = [
    ]
